[package]
name = "js-framework-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
anansi-aux = "0.14"
js-framework-comps = { path = "../js-framework-comps" , version = "*" }

[lib]
crate-type = ["cdylib"]
