[package]
name = "js-framework-benchmark-xilem"
version = "0.1.0"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"
getrandom = { version = "0.2.15", features = ["js"] }
rand = { version = "0.8.5", features = ["small_rng"] }
wasm-bindgen = "0.2.92"
web-sys = "0.3.69"
xilem_core = "0.1.0"
xilem_web = "0.1.0"

[patch.crates-io]
xilem_core = { git = "https://github.com/linebender/xilem" }
xilem_web  = { git = "https://github.com/linebender/xilem" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']
